name: morpho-blue-subgraph

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: Build of Morpho Blue Subgraph
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network: [mainnet, base, scroll, optimism, arbitrum, polygon-pos, fraxtal, ink, unichain, sonic, mode, corn]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Generate types
        run: yarn codegen

      - name: Build subgraph
        run: yarn build:${{ matrix.network }}
